spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
      name: user-service
  datasource:
    url: jdbc:mysql://mysql:3306/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_MYSQL_ROOT_USER:root}
    password: ${ENV_MYSQL_ROOT_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true


server:
  port: 8090
  jetty:
    threads:
      max: 200

